spring:
  application:
    name: notification-service

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: false
      optional: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 10

  mail:
    host: ${MAIL_HOST:smtp.msndr.net}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-discovery:8761/eureka/}