server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ivanview23/microservice-config.git
          default-label: main
          search-paths: '{application}.yml'

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
      base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: always

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.example.config: DEBUG